// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigurnaDob.Api.Data;

#nullable disable

namespace SigurnaDob.Api.Data.Migrations
{
    [DbContext(typeof(SigurnaDobDbContext))]
    [Migration("20260911122145_SeedAuthDemoData")]
    partial class SeedAuthDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_type_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ActivityTypeId")
                        .HasDatabaseName("ix_activities_activity_type_id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityParticipant", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_id");

                    b.HasKey("ActivityId", "ResidentId")
                        .HasName("pk_activity_participants");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_activity_participants_resident_id");

                    b.ToTable("activity_participants", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activity_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_types_name");

                    b.ToTable("activity_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Društvena"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kreativna"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tjelovježba"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Edukativna"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Izlet"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_roles_name");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coordinator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Caregiver"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FamilyMember"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("FamilyContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("family_contact_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("staff_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("FamilyContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_family_contact_id");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_staff_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_username");

                    b.ToTable("app_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEFLutaNEinL3QdP2YNWoaL0Qr/tPTAdVIGGkQWYoYdtWxHmHiebIUxFM3ohoxjos1Q==",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEBJLKQlZj3dSLD7NuQ99SlhqMhe0HpLJdNuq/Hs8gY92z7XYk8OA1irGdOWBAkaUzA==",
                            Username = "coordinator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOwSz/Mzqr6ENjI97rKG0mwoE4sk8cTvIxWnKGBdhQ3Gil76gFMpwule2AkdoIRFPA==",
                            StaffId = 1,
                            Username = "caregiver"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAELVhZzQ0bK3F1Lz15ptwP/gNojjzJzaj4tTXcuEKlAVQwhHq3Crgsn/2yTToOi4zmQ==",
                            Username = "familymember"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_user_id");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_role_id");

                    b.HasKey("AppUserId", "AppRoleId")
                        .HasName("pk_app_user_roles");

                    b.HasIndex("AppRoleId")
                        .HasDatabaseName("ix_app_user_roles_app_role_id");

                    b.ToTable("app_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            AppRoleId = 1
                        },
                        new
                        {
                            AppUserId = 2,
                            AppRoleId = 2
                        },
                        new
                        {
                            AppUserId = 3,
                            AppRoleId = 3
                        },
                        new
                        {
                            AppUserId = 4,
                            AppRoleId = 4
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assigned_staff_id");

                    b.Property<int>("CareTaskStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("care_task_status_id");

                    b.Property<int>("CareTaskTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("care_task_type_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_care_tasks");

                    b.HasIndex("AssignedStaffId")
                        .HasDatabaseName("ix_care_tasks_assigned_staff_id");

                    b.HasIndex("CareTaskStatusId")
                        .HasDatabaseName("ix_care_tasks_care_task_status_id");

                    b.HasIndex("CareTaskTypeId")
                        .HasDatabaseName("ix_care_tasks_care_task_type_id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_care_tasks_resident_id");

                    b.ToTable("care_tasks", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_care_task_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_care_task_statuses_name");

                    b.ToTable("care_task_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dodijeljeno"
                        },
                        new
                        {
                            Id = 3,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Izvršeno"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Otkazano"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_care_task_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_care_task_types_name");

                    b.ToTable("care_task_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Terapija"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prehrana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Higijena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pratnja"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Administrativno"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT")
                        .HasColumnName("relationship");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_family_contacts");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_family_contacts_resident_id");

                    b.ToTable("family_contacts", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("admission_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int>("ResidentStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_status_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.HasIndex("ResidentStatusId")
                        .HasDatabaseName("ix_residents_resident_status_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_residents_room_id");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_id");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_resident_documents");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_resident_documents_resident_id");

                    b.ToTable("resident_documents", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resident_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resident_statuses_name");

                    b.ToTable("resident_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "U pripremi za prijem"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Privremeno odsutan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Premješten iz doma"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arhiviran"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_status_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_room_number");

                    b.HasIndex("RoomStatusId")
                        .HasDatabaseName("ix_rooms_room_status_id");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            RoomNumber = "101",
                            RoomStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            RoomNumber = "102",
                            RoomStatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            RoomNumber = "103",
                            RoomStatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            RoomNumber = "104",
                            RoomStatusId = 2
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_room_statuses_name");

                    b.ToTable("room_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "U uporabi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Održavanje"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Izvan uporabe"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.ToTable("staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ivana Njegovateljica",
                            IsActive = true,
                            Position = "Njegovateljica"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DecidedByStaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("decided_by_staff_id");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_note");

                    b.Property<int>("FamilyContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("family_contact_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resident_id");

                    b.Property<int>("VisitRequestStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visit_request_status_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_requests");

                    b.HasIndex("DecidedByStaffId")
                        .HasDatabaseName("ix_visit_requests_decided_by_staff_id");

                    b.HasIndex("FamilyContactId")
                        .HasDatabaseName("ix_visit_requests_family_contact_id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_visit_requests_resident_id");

                    b.HasIndex("VisitRequestStatusId")
                        .HasDatabaseName("ix_visit_requests_visit_request_status_id");

                    b.ToTable("visit_requests", (string)null);
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_visit_request_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_visit_request_statuses_name");

                    b.ToTable("visit_request_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Odobreno"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odbijeno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Održano"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Otkazano"
                        });
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_activity_types_activity_type_id");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityParticipant", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Activity", "Activity")
                        .WithMany("ActivityParticipants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_participants_activities_activity_id");

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("ActivityParticipants")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_participants_residents_resident_id");

                    b.Navigation("Activity");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.FamilyContact", "FamilyContact")
                        .WithOne("AppUser")
                        .HasForeignKey("SigurnaDob.Shared.Models.AppUser", "FamilyContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_family_contacts_family_contact_id");

                    b.HasOne("SigurnaDob.Shared.Models.Staff", "Staff")
                        .WithOne("AppUser")
                        .HasForeignKey("SigurnaDob.Shared.Models.AppUser", "StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_staff_staff_id");

                    b.Navigation("FamilyContact");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.AppRole", "AppRole")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_roles_app_role_id");

                    b.HasOne("SigurnaDob.Shared.Models.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_users_app_user_id");

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTask", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Staff", "AssignedStaff")
                        .WithMany("AssignedCareTasks")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_care_tasks_staff_assigned_staff_id");

                    b.HasOne("SigurnaDob.Shared.Models.CareTaskStatus", "CareTaskStatus")
                        .WithMany("CareTasks")
                        .HasForeignKey("CareTaskStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_tasks_care_task_statuses_care_task_status_id");

                    b.HasOne("SigurnaDob.Shared.Models.CareTaskType", "CareTaskType")
                        .WithMany("CareTasks")
                        .HasForeignKey("CareTaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_tasks_care_task_types_care_task_type_id");

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("CareTasks")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_tasks_residents_resident_id");

                    b.Navigation("AssignedStaff");

                    b.Navigation("CareTaskStatus");

                    b.Navigation("CareTaskType");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("FamilyContacts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_contacts_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.ResidentStatus", "ResidentStatus")
                        .WithMany("Residents")
                        .HasForeignKey("ResidentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_residents_resident_statuses_resident_status_id");

                    b.HasOne("SigurnaDob.Shared.Models.Room", "Room")
                        .WithMany("Residents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_residents_rooms_room_id");

                    b.Navigation("ResidentStatus");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentDocument", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("ResidentDocuments")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_documents_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.RoomStatus", "RoomStatus")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_room_statuses_room_status_id");

                    b.Navigation("RoomStatus");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequest", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Staff", "DecidedByStaff")
                        .WithMany("DecidedVisitRequests")
                        .HasForeignKey("DecidedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visit_requests_staff_decided_by_staff_id");

                    b.HasOne("SigurnaDob.Shared.Models.FamilyContact", "FamilyContact")
                        .WithMany("VisitRequests")
                        .HasForeignKey("FamilyContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visit_requests_family_contacts_family_contact_id");

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("VisitRequests")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visit_requests_residents_resident_id");

                    b.HasOne("SigurnaDob.Shared.Models.VisitRequestStatus", "VisitRequestStatus")
                        .WithMany("VisitRequests")
                        .HasForeignKey("VisitRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visit_requests_visit_request_statuses_visit_request_status_id");

                    b.Navigation("DecidedByStaff");

                    b.Navigation("FamilyContact");

                    b.Navigation("Resident");

                    b.Navigation("VisitRequestStatus");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.Navigation("ActivityParticipants");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppRole", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskStatus", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskType", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("VisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.Navigation("ActivityParticipants");

                    b.Navigation("CareTasks");

                    b.Navigation("FamilyContacts");

                    b.Navigation("ResidentDocuments");

                    b.Navigation("VisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentStatus", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.RoomStatus", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Staff", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("AssignedCareTasks");

                    b.Navigation("DecidedVisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequestStatus", b =>
                {
                    b.Navigation("VisitRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
